name: Node.js Orderbook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  orderbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node nodejs-scripts/orderbook.js
